### ISSUE TITLE
StatusRuntimeException: UNAUTHENTICATED error

### ISSUE THREAD

**Issue by umyonghyun** [naver/scavenger#23]
when i start my app, i get this error message.  
where can i get a license key? is it different from api-key in scavenger.conf file?

```
2023-02-28 20:17:22.675  INFO 38534 --- [enger scheduler] c.n.s.javaagent.publishing.Publisher     : [scavenger] polling dynamic config
2023-02-28 20:17:22.679  INFO 38534 --- [enger scheduler] c.n.s.javaagent.publishing.Publisher     : [scavenger] trying to resolve collector url by accessing http://localhost:8080/javaagent/v5/initConfig
2023-02-28 20:17:24.158  INFO 38534 --- [enger scheduler] c.n.s.javaagent.publishing.Publisher     : [scavenger] resolved collector url is localhost:8080
2023-02-28 20:17:24.158  INFO 38534 --- [enger scheduler] c.n.s.javaagent.publishing.GrpcClient    : [scavenger] creating new grpc client. host is localhost:8080
2023-02-28 20:17:25.241 ERROR 38534 --- [enger scheduler] c.n.s.javaagent.scheduling.Scheduler     : [scavenger] poll config failed

sc.io.grpc.StatusRuntimeException: UNAUTHENTICATED
	at sc.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271) ~[scavenger-agent-java-1.0.3.jar:1.0.3]
	at sc.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252) ~[scavenger-agent-java-1.0.3.jar:1.0.3]
	at sc.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165) ~[scavenger-agent-java-1.0.3.jar:1.0.3]
```

**Comment by taeyeon-Kim** [comment]
@umyonghyun UNAUTHENTICATED is an exception that occurs because the API key is not valid.
The API key can be found via the UI.
First, please follow the two guides below.
1. [Create a workspace](https://github.com/naver/scavenger/blob/develop/doc/user-guide.md#create-a-workspace)
2. [Create a configuration file](https://github.com/naver/scavenger/blob/develop/doc/user-guide.md#create-a-configuration-file)

**Comment by umyonghyun** [comment]
@taeyeon-Kim, thanks for explanation. 
However I followed the guide. 
I created a scavenger's configuration file in the scavenger dashboard and used the created api key.  
<img width="487" alt="image" src="https://user-images.githubusercontent.com/35619388/222150752-9063c512-370e-41e6-a8ab-aa05f9c868d2.png">
however when I started my app, the above UNAUTHENTICATED error occurred.
```
2023-03-01 22:15:59.753  INFO 7027 --- [enger scheduler] c.n.s.javaagent.publishing.Publisher     : [scavenger] polling dynamic config
2023-03-01 22:15:59.757  INFO 7027 --- [enger scheduler] c.n.s.javaagent.publishing.Publisher     : [scavenger] trying to resolve collector url by accessing http://localhost:8080/javaagent/v5/initConfig
2023-03-01 22:16:00.107  INFO 7027 --- [enger scheduler] c.n.s.javaagent.publishing.Publisher     : [scavenger] resolved collector url is localhost:8080
2023-03-01 22:16:00.107  INFO 7027 --- [enger scheduler] c.n.s.javaagent.publishing.GrpcClient    : [scavenger] creating new grpc client. host is localhost:8080
2023-03-01 22:16:00.273 ERROR 7027 --- [enger scheduler] c.n.s.javaagent.scheduling.Scheduler     : [scavenger] poll config failed

sc.io.grpc.StatusRuntimeException: UNAUTHENTICATED
	at sc.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
	at sc.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
	at sc.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
	at sc.com.navercorp.scavenger.model.GrpcAgentServiceGrpc$GrpcAgentServiceBlockingStub.pollConfig(GrpcAgentServiceGrpc.java:263)
```

this is scanvenger collector server's log.
`[armeria-common-blocking-tasks-1-3] INFO  c.n.s.controller.AgentController - init config requested from grpc client 127.0.0.1 with licenseKey: b6dfb431-5205-442b-af29-29dee1e36090`

I wonder if there's something I'm missing.

**Comment by taeyeon-Kim** [comment]
@umyonghyun How did you run your collector and API?

**Comment by umyonghyun** [comment]
@taeyeon-Kim 
I download jar file from the provided repository (https://github.com/naver/scavenger/releases)
and ran the jar file in my local like this.
Collector :` java -jar scavenger-collector-boot-1.0.3.jar`
API : `java -Dscavenger.collector-server-url=http://localhost:8080 -jar scavenger-api-boot-1.0.3.jar`

**Comment by taeyeon-Kim** [comment]
@umyonghyun 
The collector and api have a default profile of `local`, which means they each use in-memory h2.
This means that there is no data sharing between the two modules.
Please run it like below.

* collector: `java -Dspring.profiles.active=h2 -jar scavenger-collector-boot.jar`
* api: `java -Dscavenger.collector-server-url=http://localhost:8080 -Dspring.profiles.active=h2 -jar scavenger-api-boot.jar`

**Comment by umyonghyun** [comment]
@taeyeon-Kim , I understand the situation that was the  issue. Thank you for the explanation.
collector and api must share the same repository.
It would be easier to understand if the overall architecture picture was attached to the manual.

**Comment by junoyoon** [comment]
@kojandy Hey. It's time to publish HelloWorld article. I was afraid of the case like this. :-)
