### ISSUE TITLE
scavenger-old-agent-java-1.0.0.jar JDK1.7에서 동작하지 않음

### ISSUE THREAD

**Issue by EdwardKim1129a** [naver/scavenger#31]
DEVIEW2023에서 세션에 참석한 후 사용하려고 하였더니, 시스템이 오래되어JDK 1.7을 사용해야 합니다.
하지만 해당 agent로 실행하면 다음과 같이 오류가 발생합니다.

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:382)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:397)
Caused by: java.lang.UnsupportedClassVersionError: ck/okhttp3/Authenticator : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at io.codekvast.javaagent.config.AgentConfigFactory.buildAgentConfig(AgentConfigFactory.java:134)
	at io.codekvast.javaagent.config.AgentConfigFactory.parseAgentConfig(AgentConfigFactory.java:103)
	at io.codekvast.javaagent.CodekvastAgent.premain(CodekvastAgent.java:111)
	... 6 more
FATAL ERROR in native method: processing of -javaagent failed

수정이 가능하다면 다시 배포 요청 드립니다.

**Comment by taeyeon-Kim** [comment]
@EdwardKim1129a maven central에도 반영했습니다.
